module.exports = {
    "2022": [
        "SHOULDA WON",
        "Malakas",
        "FLACCO Money FLACCO Problems",
        "The Tuacide Squad",
        "FLACCO Money FLACCO Problems",
        "My Time",
        "Fully Proofed",
        "SHOULDA WON",
        "Jeff Lowe’s Nanny....",
        "30 Cent ROY",
        "Malakas",
        "Malakas",
        "Al-G Rhythm",
        "Hey Darnold!",
        "FLACCO Money FLACCO Problems",
        "San Francisco Sharks",
        "Malakas",
        "My Time",
        "Fully Proofed",
        "FLACCO Money FLACCO Problems",
        "FLACCO Money FLACCO Problems",
        "Fully Proofed",
        "Malakas",
        "Hey Darnold!",
        "Al-G Rhythm",
        "The Tuacide Squad",
        "Hey Darnold!",
        "San Francisco Sharks",
        "FLACCO Money FLACCO Problems",
        "Fully Proofed",
        "Fully Proofed",
        "SHOULDA WON",
        "Jeff Lowe’s Nanny....",
        "Jeff Lowe’s Nanny....",
        "Malakas",
        "The Tuacide Squad"
    ],
    "2023": [
        "Al-G Rhythm",
        "The Tuacide Squad",
        "Hey Darnold!",
        "San Francisco Sharks",
        "FLACCO Money FLACCO Problems",
        "My Time",
        "Fully Proofed",
        "SHOULDA WON",
        "Jeff Lowe’s Nanny....",
        "30 Cent ROY",
        "Malakas",
        "Major League Comeback",
        "Al-G Rhythm",
        "The Tuacide Squad",
        "Hey Darnold!",
        "San Francisco Sharks",
        "FLACCO Money FLACCO Problems",
        "The Tuacide Squad",
        "Fully Proofed",
        "SHOULDA WON",
        "Jeff Lowe’s Nanny....",
        "30 Cent ROY",
        "Malakas",
        "30 Cent ROY",
        "Al-G Rhythm",
        "The Tuacide Squad",
        "Hey Darnold!",
        "San Francisco Sharks",
        "FLACCO Money FLACCO Problems",
        "My Time",
        "Fully Proofed",
        "SHOULDA WON",
        "Jeff Lowe’s Nanny....",
        "30 Cent ROY",
        "Malakas",
        "30 Cent ROY"
    ],
    "2024": [
        "Al-G Rhythm",
        "The Tuacide Squad",
        "Hey Darnold!",
        "San Francisco Sharks",
        "FLACCO Money FLACCO Problems",
        "My Time",
        "Fully Proofed",
        "SHOULDA WON",
        "Jeff Lowe’s Nanny....",
        "30 Cent ROY",
        "Malakas",
        "Major League Comeback",
        "Al-G Rhythm",
        "The Tuacide Squad",
        "Hey Darnold!",
        "San Francisco Sharks",
        "FLACCO Money FLACCO Problems",
        "My Time",
        "Fully Proofed",
        "SHOULDA WON",
        "Jeff Lowe’s Nanny....",
        "30 Cent ROY",
        "Malakas",
        "Hey Darnold!",
        "Al-G Rhythm",
        "The Tuacide Squad",
        "Hey Darnold!",
        "San Francisco Sharks",
        "FLACCO Money FLACCO Problems",
        "My Time",
        "Fully Proofed",
        "SHOULDA WON",
        "Jeff Lowe’s Nanny....",
        "30 Cent ROY",
        "Malakas",
        "Major League Comeback"
    ]
}